RobsWebsiteV2/Controllers/BaseCurveController.cs
using Microsoft.AspNetCore.Mvc;
using RobsWebsiteV2.CalcModels.BaseCurve;
using OpticianMathLibrary;

namespace RobsWebsiteV2.Controllers
{
    public class BaseCurveController : Controller
    {
        public IActionResult VogelsRulePlus(VogelsRulePlusModel baseCurve)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            baseCurve.Result = BaseCurve.VogelsRulePlus(baseCurve.SpherePower, baseCurve.CylinderPower);
            return View(baseCurve);
        }

        public IActionResult VogelsRuleMinus(VogelsRuleMinusModel baseCurve)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            baseCurve.Result = BaseCurve.VogelsRuleMinus(baseCurve.SpherePower, baseCurve.CylinderPower);
            return View(baseCurve);
        }

        public IActionResult BoddyFormula(BoddyFormula baseCurve)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            baseCurve.Result = BaseCurve.BoddyFormula(baseCurve.SpherePower, baseCurve.CylinderPower, baseCurve.AddPower);
            return View(baseCurve);
        }
    }
}

RobsWebsiteV2/Controllers/CalculatorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RobsWebsiteV2.Controllers
{
    public class CalculatorsController : Controller
    {
        public IActionResult CalculatorsHome ()
        {
            return View();
        }
    }
}

RobsWebsiteV2/Views/Calculators/CalculatorsHome.cshtml
@{
    ViewData["Title"] = "Calculators";
}

<div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header text-dark">Base Curve</div>
    <div class="card-body text-dark">
        <ul class="list-unstyled">
            <li>
                <a asp-controller="BaseCurve" asp-action="VogelsRulePlus">VogelsRulePlus</a>
            </li>
            <li>
                <a asp-controller="BaseCurve" asp-action="VogelsRuleMinus">VogelsRuleMinus</a>
            </li>
            <li>
                <a asp-controller="BaseCurve" asp-action="BoddyFormula">BoddyFormula</a>
            </li>
        </ul>
    </div>
</div>